remote_theme: pmarsceill/just-the-docs


#Site settings
title: GTFO Modding Wiki
description: Your one stop spot for everything modding!
#baseurl: "/wiki"
#url: "https://gtfo-modding.github.io"

logo: "/assets/images/dauna.png"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Modding Discord":
    - "https://discord.gg/arYsUs5K8X"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/GTFO-Modding/GTFO-Modding-Wiki" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme supports "light" (default) and "dark"
color_scheme: dark