title: "GTFO Modding Wiki"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
baseurl: "/wiki"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Join the modding Discord!":
    - "https://discord.gg/rRMPtv4FAh"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Define Jekyll collections
collections:
  # Define a collection named "gamedata", its documents reside in the "_gamedata" directory
  gamedata:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    gamedata:
      # Give the collection a name
      name: GameData Documentation
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false