title: "GTFO Modding Wiki"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
baseurl: "/Wiki"

logo: "/assets/images/dauna.png"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Join the modding Discord!":
    - "https://discord.gg/rRMPtv4FAh"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false