name: Wiki CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

#  deploy:
#    needs: build
#    runs-on: ubuntu-20.04
#    steps: